import type { Metadata } from 'next'
import { Scada } from 'next/font/google'
import './globals.css'

//const inter = Inter({ subsets: ['latin'] })
const inter = Scada({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Julio's Home Page",
  description: 'Generated by Vercel',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  )
}
